_DERPADERPA_dami = (vehicle player);
_DERPADERPA_dami addMagazine 'Skin_Sniper1_DZ';
_DERPADERPA_dami addMagazine 'ItemMorphine';
_DERPADERPA_dami addMagazine 'ItemBloodbag';
_DERPADERPA_dami addMagazine 'ItemPainkiller'; 
_DERPADERPA_dami addMagazine 'ItemEpinephrine';
_DERPADERPA_dami addMagazine 'ItemSodaPepsi';
_DERPADERPA_dami addMagazine 'FoodSteakCooked';
_DERPADERPA_dami addMagazine 'ItemBandage';
_DERPADERPA_dami addMagazine 'ItemBandage';
_DERPADERPA_dami addWeapon 'Binocular_Vector';
_DERPADERPA_dami addWeapon 'NVGoggles';
_DERPADERPA_dami addWeapon 'ItemGPS';
_DERPADERPA_dami addWeapon 'ItemCompass';
_DERPADERPA_dami addWeapon 'ItemMap';
_DERPADERPA_dami addWeapon 'ItemWatch';
_DERPADERPA_dami addWeapon 'ItemHatchet';
_DERPADERPA_dami addWeapon 'ItemKnife';
_DERPADERPA_dami addWeapon 'Itemmatchbox';
_DERPADERPA_dami addWeapon 'Itemetool';
_DERPADERPA_dami addWeapon 'Itemtoolbox';
_DERPADERPA_dami addBackpack 'DZ_ALICE_Pack_EP1';
(Unitbackpack _DERPADERPA_dami) addMagazineCargo ['ItemBloodbag', 4];
(Unitbackpack _DERPADERPA_dami) addMagazineCargo ['ItemEpinephrine', 4];
(Unitbackpack _DERPADERPA_dami) addMagazineCargo ['ItemSodaPepsi', 4];
(Unitbackpack _DERPADERPA_dami) addMagazineCargo ['ItemBandage', 4];
(Unitbackpack _DERPADERPA_dami) addMagazineCargo ['FoodSteakCooked', 2];
(Unitbackpack _DERPADERPA_dami) addMagazineCargo ['ItemMorphine', 2];