_DERPADERPA_dami = (vehicle player);
_DERPADERPA_dami addWeapon 'FN_FAL';
_DERPADERPA_dami addMagazine '20Rnd_762x51_FNFAL';
_DERPADERPA_dami addMagazine '20Rnd_762x51_FNFAL';
_DERPADERPA_dami addMagazine '20Rnd_762x51_FNFAL';
_DERPADERPA_dami addMagazine '20Rnd_762x51_FNFAL';
_DERPADERPA_dami addMagazine '20Rnd_762x51_FNFAL';
_DERPADERPA_dami addMagazine 'Skin_Sniper1_DZ';
_DERPADERPA_dami addMagazine 'ItemMorphine';
_DERPADERPA_dami addMagazine 'ItemBloodbag';
_DERPADERPA_dami addMagazine 'ItemPainkiller'; 
_DERPADERPA_dami addMagazine 'ItemEpinephrine';
_DERPADERPA_dami addMagazine 'ItemSodaPepsi';
_DERPADERPA_dami addMagazine 'FoodSteakCooked';
_DERPADERPA_dami addWeapon 'M9SD';
_DERPADERPA_dami addMagazine '15Rnd_9x19_M9SD';
_DERPADERPA_dami addMagazine '15Rnd_9x19_M9SD';
_DERPADERPA_dami addMagazine '15Rnd_9x19_M9SD';
_DERPADERPA_dami addMagazine '15Rnd_9x19_M9SD';
_DERPADERPA_dami addMagazine 'ItemBandage';
_DERPADERPA_dami addMagazine 'ItemBandage';
_DERPADERPA_dami addMagazine '1Rnd_HE_M203';
_DERPADERPA_dami addMagazine 'FlareGreen_M203';
_DERPADERPA_dami addWeapon 'Binocular_Vector';
_DERPADERPA_dami addWeapon 'NVGoggles';
_DERPADERPA_dami addWeapon 'ItemGPS';
_DERPADERPA_dami addWeapon 'ItemCompass';
_DERPADERPA_dami addWeapon 'ItemMap';
_DERPADERPA_dami addWeapon 'ItemWatch';
_DERPADERPA_dami addWeapon 'ItemHatchet';
_DERPADERPA_dami addWeapon 'ItemKnife';
_DERPADERPA_dami addWeapon 'Itemmatchbox';
_DERPADERPA_dami addWeapon 'Itemetool';
_DERPADERPA_dami addWeapon 'Itemtoolbox';
_DERPADERPA_dami addBackpack 'DZ_ALICE_Pack_EP1';
(Unitbackpack _DERPADERPA_dami) addMagazineCargoGlobal ['ItemBloodbag', 4];
(Unitbackpack _DERPADERPA_dami) addMagazineCargoGlobal ['ItemEpinephrine', 4];
(Unitbackpack _DERPADERPA_dami) addMagazineCargoGlobal ['ItemSodaPepsi', 4];
(Unitbackpack _DERPADERPA_dami) addMagazineCargoGlobal ['ItemBandage', 4];
(Unitbackpack _DERPADERPA_dami) addMagazineCargoGlobal ['FoodSteakCooked', 2];
(Unitbackpack _DERPADERPA_dami) addMagazineCargoGlobal ['ItemMorphine', 2];